# Generated by Django 2.2.5 on 2019-09-25 17:45

from django.db import migrations, models
import django.db.models.deletion
import martor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', martor.models.MartorField(max_length=4096)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elements.Element')),
                ('algorithm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='algorithmical_linker', to='elements.Element')),
                ('semantic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantical_linker', to='elements.Element')),
            ],
            options={
                'unique_together': {('semantic', 'algorithm')},
            },
            bases=('elements.element',),
        ),
        migrations.CreateModel(
            name='ElementLink',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elements.Element')),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='define_links', to='elements.Linker')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_endpoints', to='elements.Element')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_startpoints', to='elements.Element')),
            ],
            options={
                'unique_together': {('subject', 'object', 'link')},
            },
            bases=('elements.element',),
        ),
        migrations.AddField(
            model_name='element',
            name='links',
            field=models.ManyToManyField(through='elements.ElementLink', to='elements.Element'),
        ),
    ]
