# Generated by Django 2.2.5 on 2019-09-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20190927_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserElement',
        ),
    ]
