# Generated by Django 2.2.5 on 2019-09-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_delete_userelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='content',
        ),
        migrations.AddField(
            model_name='element',
            name='data',
            field=models.BinaryField(null=True),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['uid'], name='elements_el_uid_e7a15d_idx'),
        ),
    ]
