# Generated by Django 2.2.5 on 2019-09-17 08:57

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0008_auto_20190907_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='description',
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
