# Generated by Django 2.2.5 on 2019-09-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0011_auto_20190923_1805'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elementlink',
            unique_together={('node', 'sibling', 'type')},
        ),
    ]
