# Generated by Django 2.2.5 on 2019-09-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0012_auto_20190923_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementlink',
            name='id',
        ),
        migrations.AddField(
            model_name='elementlink',
            name='element_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elements.Element'),
            preserve_default=False,
        ),
    ]
