# Generated by Django 2.2.5 on 2019-09-16 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('is_virtual', models.BooleanField(default=True)),
                ('email_is_valid', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['-creation_date'], name='identities__creatio_edacea_idx'),
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['key'], name='identities__key_fd3127_idx'),
        ),
    ]
