# Generated by Django 2.2.4 on 2019-09-06 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20190905_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementmetadata',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elementmetadata',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='elementmetadata',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_elements', to=settings.AUTH_USER_MODEL),
        ),
    ]
