# Generated by Django 2.2.4 on 2019-09-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_auto_20190907_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='renderer',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
