# Generated by Django 2.2.5 on 2019-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0009_auto_20190917_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
