# Generated by Django 2.2.5 on 2019-09-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0010_auto_20190917_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementlinktype',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
