# Generated by Django 2.2.5 on 2019-09-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0013_auto_20190924_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementlink',
            old_name='sibling',
            new_name='sibbling',
        ),
        migrations.AlterUniqueTogether(
            name='elementlink',
            unique_together={('node', 'sibbling', 'type')},
        ),
    ]
