# Generated by Django 2.2.3 on 2019-07-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offhistory',
            name='reason',
            field=models.TextField(default='system'),
        ),
    ]
