# Generated by Django 2.2.3 on 2019-07-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0002_offhistory_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_on', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(default='system')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OffAccount.OffAccount')),
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OffAccount.OffCredit')),
            ],
        ),
        migrations.DeleteModel(
            name='OffHistory',
        ),
        migrations.AddIndex(
            model_name='offtransaction',
            index=models.Index(fields=['account'], name='OffAccount__account_7638bd_idx'),
        ),
        migrations.AddIndex(
            model_name='offtransaction',
            index=models.Index(fields=['-entry_on'], name='OffAccount__entry_o_d4a59c_idx'),
        ),
    ]
