# Generated by Django 2.2.3 on 2019-07-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0003_auto_20190712_0846'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offtransaction',
            name='OffAccount__account_7638bd_idx',
        ),
    ]
