# Generated by Django 2.2.3 on 2019-07-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0005_offaccount_system_account'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offtransaction',
            name='OffAccount__entry_o_d4a59c_idx',
        ),
        migrations.RenameField(
            model_name='offtransaction',
            old_name='entry_on',
            new_name='created_on',
        ),
        migrations.AddIndex(
            model_name='offtransaction',
            index=models.Index(fields=['-created_on'], name='OffAccount__created_8bdf54_idx'),
        ),
    ]
