# Generated by Django 2.2 on 2019-07-17 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0006_auto_20190714_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcredit',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OffAccount.OffAccount'),
        ),
        migrations.AlterField(
            model_name='offcredit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OffAccount.OffAccount'),
        ),
        migrations.AlterField(
            model_name='offtransaction',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OffAccount.OffCredit'),
        ),
    ]
