# Generated by Django 2.2 on 2019-07-17 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0007_auto_20190717_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcredit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
