# Generated by Django 2.2 on 2019-07-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0008_auto_20190717_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offtransaction',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='offtransaction',
            name='account',
        ),
        migrations.AddField(
            model_name='offtransaction',
            name='account_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_debit', to='OffAccount.OffAccount'),
        ),
        migrations.AddField(
            model_name='offtransaction',
            name='account_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_credit', to='OffAccount.OffAccount'),
        ),
    ]
