# Generated by Django 2.2 on 2019-07-17 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0009_auto_20190717_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offtransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
