# Generated by Django 2.2 on 2019-07-21 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OffAccount', '0010_auto_20190717_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offcredit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='offcredit',
            name='created_on',
        ),
        migrations.CreateModel(
            name='OffCreditCreation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(default=1.0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='offcredit',
            name='creation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='OffAccount.OffCreditCreation'),
        ),
    ]
