# Generated by Django 2.2 on 2019-07-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0011_auto_20190721_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offcreditcreation',
            name='value',
        ),
    ]
