# Generated by Django 2.2 on 2019-07-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0012_remove_offcreditcreation_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offcredit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='offtransaction',
            name='credit',
        ),
        migrations.AddField(
            model_name='offtransaction',
            name='creation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='OffAccount.OffCreditCreation'),
        ),
        migrations.AlterField(
            model_name='offcredit',
            name='creation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='OffAccount.OffCreditCreation'),
        ),
    ]
