# Generated by Django 2.2 on 2019-07-21 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0013_auto_20190721_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='offtransaction',
            name='credit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='OffAccount.OffCredit'),
            preserve_default=False,
        ),
    ]
