# Generated by Django 2.2 on 2019-07-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0014_offtransaction_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offtransaction',
            name='creation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OffAccount.OffCreditCreation'),
        ),
    ]
