# Generated by Django 2.2 on 2019-07-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0015_auto_20190721_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcreditcreation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OffAccount.OffAccount'),
        ),
    ]
