# Generated by Django 2.2 on 2019-07-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0017_auto_20190722_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offtransaction',
            name='transtype',
            field=models.CharField(choices=[('CREATION', 'Création'), ('EXCHANGE', 'Échange')], max_length=10),
        ),
    ]
