# Generated by Django 2.2 on 2019-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0018_auto_20190726_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offtransaction',
            name='transtype',
            field=models.CharField(choices=[('CREATION', 'CREATION'), ('EXCHANGE', 'EXCHANGE')], max_length=10),
        ),
    ]
