# Generated by Django 2.2 on 2019-08-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffAccount', '0019_auto_20190820_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offtransaction',
            name='transtype',
            field=models.CharField(choices=[('CREATION', 'Création'), ('EXCHANGE', 'Échange')], max_length=10),
        ),
    ]
