#!/usr/bin/env bash

error() {
    echo "$@"
    exit 1
}

preconditions() {
    [[ -f scripts/app ]] || error "Run from off root"
}

makemessages() {
    python manage.py makemessages -l fr
}

compilemessages() {
    python manage.py compilemessages -l fr
}

run() {
    compilemessages
    python manage.py runserver 0.0.0.0:8000
}

debug() {
   DJANGO_DEBUG=1 python manage.py runserver 0.0.0.0:8000 
}

main() {
    preconditions
    local cmd="$1" ; shift || error "Missing command"
    
    $cmd "$@"
}

main "$@"