# Generated by Django 2.2 on 2019-08-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffIdentity', '0002_auto_20190716_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='offidentity',
            name='email_is_valid',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
