# Generated by Django 2.2 on 2019-08-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffIdentity', '0004_auto_20190819_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='offidentity',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
