# Generated by Django 2.2.5 on 2019-09-17 08:57

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0009_auto_20190917_0857'),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elements.Element')),
                ('content', martor.models.MartorField(blank=True, null=True)),
            ],
            bases=('elements.element',),
        ),
    ]
